DATA : LOC TYPE STRING VALUE '서울시 종로구 교보생명빌딩',
       FIRST TYPE STRING,
       SECOND TYPE STRING,
       THIRD TYPE STRING.

SPLIT LOC AT ' ' INTO FIRST SECOND THIRD.

WRITE: FIRST,
       /SECOND,
       / THIRD.