DATA : PA_8DATA1 TYPE C LENGTH 8 VALUE 'ABCDEFGH',
       PA_8DATA2 TYPE C LENGTH 8 VALUE 'ABCDEFGH',
       PA_4DATA1 TYPE C LENGTH4,
       PA_4DATA2 TYPE C LENGTH4.

PA 4 DATA1 = PA 8 DATA1 + 1(4).
PA_4DATA2 = PA_8DATA2+3(4).

WRITE: '요구사항을 만족하도록 8자리 데이터를 출력한 결과',
       /PA_4DATA1,
       /PA_4DATA2.