DATA : PA_DATELIKESY-DATUM,
       PA_AFTER_DATELIKESY-DATUM.

PA_DATE = SY-DATUM.
PA_AFTER_DATE = PA_DATE+4.

DATA : PA_STRING TYPE C LENGTH 8,
       YEAR TYPE STRING,
       MONTH TYPE STRING,
       DAY TYPE STRING.

PA_STRING = PA_AFTER_DATE.
WRITE : /PA_AFTER_DATE.