*&------------------------------------------------ ---------------------*
*&Report YTEST_CS_PA04_01
*&------------------------------------------------ ---------------------*
*&
*&------------------------------------------------ ---------------------*

REPORT YTEST_CS_PA04_01.

TABLES SCARR.
TABLES SFLIGHT.

TYPES : BEGIN OF TP_DEF,
        CARRID TYPE SFLIGHT-CARRID,
        CONNID TYPE SFLIGHT-CONNID,
        FLDATE TYPE SFLIGHT-FLDATE,
        PRICE TYPE SFLIGHT-PRICE,
        CARRNAME TYPE SCARR-CARRNAME,
        CURRCODE TYPE SCARR-CURRCODE,
        URL TYPE SCARR-URL,
END OF TP_DEF.

DATA : LS_DATA TYPE TP_DEF.
DATA : LS_TABLE TYP TABLE OF TP_DEF.

SELECT SC~CARRID SF~CONNID SF~FLDATE SF~PRICE SC~CARRNAME SC~CURRCODE SC~URL
INTO CORRESPONDING FIELDS OF TABLE LS_TABLE
FROM SFLIGHT AS SF
INNER JOIN SCARR AS SC
ON SC~CARRID = SF~CARRID.

LOOP AT LS_TABLE INTO LS_DATA.
WRITE : / SY-TABIX, LS_DATA-CARRID, LS_DATA-CONNID, LS_DATA-FLDATE, LS_DATA-PRICE, LS_DATA-CARRNAME, LS_DATA-CURRCODE, LS_DATA-URL , / .

ENDLOOP.