*&------------------------------------------------ ---------------------*
*&Report YTEST_CS_PA04_02
*&------------------------------------------------ ---------------------*
*&
*&------------------------------------------------ ---------------------*
REPORT YTEST_CS_PA04_02.

TABLES SCARR.
TABLES SFLIGHT.

TYPES:  BEGIN OF TP_DEF,
        CARRID TYPE SFLIGHT-CARRID,
        CONNID TYPE SFLIGHT-CONNID,
        FLDATE TYPES FLIGHT-FLDATE,
        PRICE TYPE SFLIGHT-PRICE,
        CARRNAME TYPE SCARR-CARRNAME,
        CURRCODE TYPE SCARR-CURRCODE,
        URL TYPE SCARR-URL,
END OF TP_DEF.

DATA: LS_DATATYPETP_DEF.
DATA: LS_TABLETYPETABLEOFTP_DEF.

SELECT SC~CARRID SF~CONNID SF~FLDATE SF~PRICE SC~CARRNAME SC~CURRCODE SC~URL
INTO CORRESPONDING FIELDS OF TABLE LS_TABLE
FROM SFLIGHT AS SF
INNER JOIN SCARR AS SC
ON SC~CARRID = SF~CARRID.

* 중복제거
DELETE ADJACENT DUPLICATES FROM LS_TABLE.

* READ TABLE 써서 출력
LOOP AT LS_TABLE INTO LS_DATA.
    READ TABLE LS_TABLE FROM LS_DATA INTO LS_DATA.
    WRITE: LS_DATA-CARRID, LS_DATA-CARRNAME, LS_DATA-PRICE, LS_DATA-FLDATE, LS_DATA-CURRCODE, LS_DATA-URL, /.
ENDLOOP.